outdir: /hy-tmp/100_outputs  # to be overriden in CLI

model:
  path: /hy-tmp/SD2-1-base  
  pipeline_path: /hy-tmp/MyREMOVAL/pipeline_mine_refine.py

dataset:
  datadir: /hy-tmp/DATA/test_sampled_100
  img_suffix: .jpg
  #pad_out_to_modulo: 8
out_suffix: _removed_
out_ext: .png
seed: 321
save:
  result: True
  tile: True
  mask: True
  resize_img: True
