outdir: /hy-tmp/outputs_mine_fu  # to be overriden in CLI

model:
  path: /hy-tmp/SD2-1-base  
  pipeline_path: /hy-tmp/MyREMOVAL/pipeline_inp.py

dataset:
  datadir: /hy-tmp/DATA/sample
  img_suffix: .jpg
  #pad_out_to_modulo: 8
out_suffix: _removed_
out_ext: .png
seed: 123
save:
  result: True
  tile: True
  mask: True
  resize_img: True