outdir: /hy-tmp/outputs  # to be overriden in CLI

model:
  path: /hy-tmp/SD2-1-base  
  pipeline_path: /hy-tmp/MyREMOVAL/pipeline_mine.py

dataset:
  datadir: /hy-tmp/DATA/test_sampled1
  img_suffix: .jpg
  #pad_out_to_modulo: 8
out_key: inpainted