outdir: /hy-tmp/sd_outputs  # to be overriden in CLI

model:
  path: /hy-tmp/SD2-1-base

dataset:
  datadir: /hy-tmp/test_sampled1
  img_suffix: .jpg
  #pad_out_to_modulo: 8
out_key: sd
out_ext: .png
seed: 123
save:
  result: True
  tile: True