outdir: ../out_test  # to be overriden in CLI

model:
  path: ../SD2-1-base  
  pipeline_path: ./pipelines/pipeline_inp.py

dataset:
  datadir: ../DATA/sample
  img_suffix: .jpg
  #pad_out_to_modulo: 8
out_suffix: _removed_
out_ext: .png
seed: 123
save:
  result: True
  tile: False
  mask: False
  resize_img: False
